# NumPy Exercises 


#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create an array of all the even integers from 10 to 50

In [6]:
array=np.arange(10,50,2)
print("Array of all the even integers from 10 to 50")
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
my_matrix
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(2)

array([0.80335808, 0.96201404])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
r = np.random.normal(size=25)
print(r)

[-2.39284119  0.78299773  0.0186914   1.89279111 -0.09517652  1.44889935
 -0.29205522 -0.26370015  1.36029361  0.18722616  1.32033039  0.47565774
 -1.43145467 -0.18516547 -1.80098857  0.83228383 -0.06194396  0.56340605
  1.14836807  0.66295691 -0.33860552  0.46050245  1.00698801 -0.22588297
  0.94967254]


#### Create the following matrix:

In [11]:
>>> import numpy as np

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
num_line = np.linspace(0, 1, 20)
print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[0:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [15]:
array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[1,2]

In [ ]:
8

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:2, 1].reshape(2,1)

array([[2],
       [7]])

In [17]:
array([[2],
       [7]])

TypeError: 'numpy.ndarray' object is not callable

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2,:]

array([11, 12, 13, 14, 15])

In [21]:
array([11, 12, 13, 14, 15])

TypeError: 'numpy.ndarray' object is not callable

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

#### Get the standard deviation of the values in mat

In [ ]:
mat.std()

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=1)

# Great Job!